### ISSUE TITLE
Ubuntu 14.04

### ISSUE THREAD

**Issue by ArulselvanMadhavan** [didier-wenzek/ocaml-kafka#21]
I'm unable to compile this on Ubuntu 14.04. I tried posting the error on discord but haven't been able to figure out
```bash
#=== ERROR while compiling kafka.0.4 ==========================================#
# context     2.0.7 | linux/x86_64 | ocaml-base-compiler.4.05.0 | https://opam.ocaml.org#c23dfbd9
# path        ~/locations-consumer/_opam/.opam-switch/build/kafka.0.4
# command     ~/.opam/opam-init/hooks/sandbox.sh build jbuilder build -p kafka -j 1
# exit-code   1
# env-file    ~/.opam/log/kafka-25955-d2c37b.env
# output-file ~/.opam/log/kafka-25955-d2c37b.out
### output ###
# ocaml_lwt_kafka.c:112:3: warning: implicit declaration of function ‘rd_kafka_consume_queue’ [-Wimplicit-function-declaration]
# [...]
# ocaml_lwt_kafka.c:112:16: warning: assignment makes pointer from integer without a cast [enabled by default]
#    job->message = rd_kafka_consume_queue(job->queue, job->timeout);
#                 ^
# ocaml_lwt_kafka.c: At top level:
# ocaml_lwt_kafka.c:241:3: error: unknown type name ‘rd_kafka_queue_t’
#    rd_kafka_queue_t *queue;
#    ^
# ocaml_lwt_kafka.c: In function ‘worker_consume_batch_queue’:
# ocaml_lwt_kafka.c:255:3: warning: implicit declaration of function ‘rd_kafka_consume_batch_queue’ [-Wimplicit-function-declaration]
#    job->actual_msg_count = rd_kafka_consume_batch_queue(job->queue, job->timeout, job->messages, job->msg_count);
```
Thanks!

**Comment by didier-wenzek** [comment]
Can you provide the exact sequence of commands you used? Which build command? From which directory?

**Comment by ArulselvanMadhavan** [comment]
@didier-wenzek Yes.
I created a new project with ocaml 4.05.0 as the base compiler and did `opam install kafka` on an ubuntu 14.04 to get the above error. 

If it helps, I did the same thing on an Ubuntu 18 machine and it got installed successfully

**Comment by didier-wenzek** [comment]
The queue features have been introduced by the [version 0.8.4 of librdkafka](https://github.com/edenhill/librdkafka/releases/tag/0.8.4) released on Aug 18, 2014.

I cannot check which version of librdkafka is packaged by Ubuntu 14.04, since the information is no more available on the Ubuntu web site. For [Ubuntu 16.04](https://packages.ubuntu.com/xenial/librdkafka-dev) it should be okay, even if the version of librdkafka is quite old (May 17, 2016).

To use ocaml-kafka on Ubuntu 14.04, you need to [install librdkafka from source](https://github.com/edenhill/librdkafka#build-from-source).
