### ISSUE TITLE
delivery_callback is GC unsafe

### ISSUE THREAD

**Issue by ygrek** [didier-wenzek/ocaml-kafka#5]
```
  if (Is_block(caml_delivery_callback)) {
     caml_callback = Field(caml_delivery_callback, 0);
     rd_kafka_conf_set_opaque(conf, (void*) caml_callback);
     rd_kafka_conf_set_dr_cb(conf, ocaml_kafka_delivery_callback);
  } 
```

this stores OCaml value in the C structure without registering as GC root

**Comment by didier-wenzek** [comment]
Indeed, there are missing calls to caml_register_generational_global_root and caml_remove_generational_global_root . Thanks.

Adding these calls implies a bit of rework, since the C structure is opaque with no way to get  the actual address of the candidate GC root. Hence, the caml_callback value has to be wrapped into an intermediate C structure.

**Comment by didier-wenzek** [comment]
A similar work has to be done for the partitioner_callback.

**Comment by didier-wenzek** [comment]
Test checking the delivery callback is properly registered:
 https://github.com/didier-wenzek/ocaml-kafka/commit/7db85fa93feada2cae7eed088c51ef179c7d7b88
